version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db-primary
      - db-standby
    environment:
      PGADMIN_DEFAULT_EMAIL: jeniatr3@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwe
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.pgadmin
      - pgadmin:/var/lib/pgadmin

  db-primary:
    container_name: db-primary
    restart: unless-stopped
    image: postgres:11 
    env_file:
      - ./primary/database.env
    volumes:
      - ./primary/data/:/var/lib/postgresql/data/

  db-standby:
    container_name: db-standby
    restart: unless-stopped
    image: postgres:11
    depends_on:
      - db-primary
    env_file:
      - ./standby/database.env
    volumes:
      - ./standby/data/:/var/lib/postgresql/data/

volumes:
    database-data:
    pgadmin: