---
- hosts: PROD_WEB
  user: "{{ USER }}"
  vars_files:
    - ../vars.yml

  tasks:

    - name: Setup Rsync
      package:
        name: rsync
        state: present
      become: true

    - name: Copy app to directory
      ansible.posix.synchronize:
        src: "{{ LOCAL_PROJECT_HOME }}"
        dest: "{{ PROJECT_HOME }}"
        # recursive: yes
        rsync_opts:
          - "--exclude=.git"