---
- hosts: PROD_WEB
  become: true
  remote_user: root
  vars_files:
    - ../vars.yml

  tasks:
    - name: Добавить пользователя 'anscfg' с добавлением его в группу 'sudo'.
      user:
        name: anscfg
        password: "{{ passAnsCfg }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Создать 2048-битовый SSH ключ для anscfg в ~anscfg/.ssh/id_rsa
      user:
        name: anscfg
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: Установить authorized key из файла id_rsa.pub
      authorized_key:
        user: anscfg
        state: present
        key: "{{ lookup('file', '/home/jenia/.ssh/id_rsa.pub') }}"
